/* ============================================================
   TRIPTAILOR — Country metadata
   60 destinations curated by hand (iso, city, tags, budget, hi).
   Climate fields (scores, tempLo, tempHi, rainDays) come either from
   the hand-curated baseline below OR from src/data/climate.json,
   which is regenerated by `scripts/fetch-climate.ts` (Open-Meteo).
   When climate.json has an entry for a given ISO, it OVERRIDES the
   baseline at module-load time.
   ============================================================ */

import climateOverrides from './climate.json';

export type ContinentId = 'eu' | 'as' | 'af' | 'na' | 'sa' | 'oc';
export type Tag = 'plage' | 'culture' | 'aventure' | 'gastro' | 'ville' | 'nature';

export interface Country {
  id: string;            // 3-digit ISO numeric (matches world-atlas)
  iso: string;           // ISO-2
  name: string;
  city: string;
  cont: ContinentId;
  lat: number;
  lon: number;
  budget: 1 | 2 | 3;
  tags: Tag[];
  scores: number[];      // 12 monthly scores (Jan→Dec)
  tempLo: number;
  tempHi: number;
  rainDays: number;
  hi: string;
}

export interface Agent {
  id: 'meteo' | 'budget' | 'safety' | 'plan';
  name: string;
  color: string;
  icon: string;
}

export const months = ['Jan','Fév','Mars','Avr','Mai','Juin','Juil','Août','Sept','Oct','Nov','Déc'] as const;
export const monthsFull = ['Janvier','Février','Mars','Avril','Mai','Juin','Juillet','Août','Septembre','Octobre','Novembre','Décembre'] as const;

export const continents: { id: 'all' | ContinentId; label: string }[] = [
  { id: 'all', label: 'Tout le monde' },
  { id: 'eu',  label: 'Europe' },
  { id: 'as',  label: 'Asie' },
  { id: 'af',  label: 'Afrique' },
  { id: 'na',  label: 'Amérique N.' },
  { id: 'sa',  label: 'Amérique S.' },
  { id: 'oc',  label: 'Océanie' },
];

const COUNTRIES_BASELINE: Country[] = [
  // EUROPE
  { id:'620', iso:'PT', name:'Portugal',     city:'Lisbonne',     cont:'eu', lat:38.7,   lon:-9.1,    budget:2, tags:['plage','culture','gastro'],
    scores:[55,58,68,82,87,85,80,78,84,80,68,58], tempLo:11, tempHi:23, rainDays:4, hi:"Lisbonne, Porto, l'Alentejo en fleur" },
  { id:'724', iso:'ES', name:'Espagne',      city:'Séville',      cont:'eu', lat:37.4,   lon:-5.99,   budget:2, tags:['culture','gastro','ville'],
    scores:[55,60,72,84,88,82,72,70,78,82,70,58], tempLo:12, tempHi:26, rainDays:3, hi:"Andalousie en avril, fiestas de mai" },
  { id:'380', iso:'IT', name:'Italie',       city:'Rome',         cont:'eu', lat:41.9,   lon:12.5,    budget:2, tags:['culture','gastro','ville'],
    scores:[50,55,65,78,86,84,76,74,82,80,65,55], tempLo:13, tempHi:24, rainDays:5, hi:"Toscane, lacs lombards, Pouilles" },
  { id:'250', iso:'FR', name:'France',       city:'Paris',        cont:'eu', lat:48.85,  lon:2.35,    budget:2, tags:['culture','gastro','ville'],
    scores:[40,45,58,70,80,82,78,76,74,62,48,40], tempLo:10, tempHi:20, rainDays:7, hi:"Provence, Bretagne, Côte d'Azur" },
  { id:'300', iso:'GR', name:'Grèce',        city:'Athènes',      cont:'eu', lat:37.97,  lon:23.72,   budget:2, tags:['plage','culture'],
    scores:[52,55,62,75,84,86,82,80,84,78,65,55], tempLo:14, tempHi:24, rainDays:3, hi:"Cyclades, Crète, Athènes douce" },
  { id:'792', iso:'TR', name:'Turquie',      city:'Istanbul',     cont:'eu', lat:41.0,   lon:28.97,   budget:1, tags:['culture','gastro'],
    scores:[40,45,58,72,82,78,72,70,76,74,60,48], tempLo:10, tempHi:22, rainDays:5, hi:"Cappadoce, Istanbul, côte égéenne" },
  { id:'826', iso:'GB', name:'Royaume-Uni',  city:'Londres',      cont:'eu', lat:51.5,   lon:-0.13,   budget:3, tags:['culture','ville'],
    scores:[35,38,48,58,68,72,70,68,64,52,42,36], tempLo:8,  tempHi:18, rainDays:9, hi:"Pubs, jardins anglais, festivals" },
  { id:'276', iso:'DE', name:'Allemagne',    city:'Berlin',       cont:'eu', lat:52.5,   lon:13.4,    budget:2, tags:['culture','ville'],
    scores:[32,38,48,60,72,78,76,72,68,55,42,32], tempLo:9,  tempHi:20, rainDays:8, hi:"Berlin, Bavière, vallée du Rhin" },
  { id:'528', iso:'NL', name:'Pays-Bas',     city:'Amsterdam',    cont:'eu', lat:52.37,  lon:4.9,     budget:3, tags:['culture','ville'],
    scores:[35,40,50,62,72,74,72,70,66,55,42,35], tempLo:8,  tempHi:18, rainDays:9, hi:"Tulipes en mai, canaux, vélo" },
  { id:'752', iso:'SE', name:'Suède',        city:'Stockholm',    cont:'eu', lat:59.33,  lon:18.07,   budget:3, tags:['nature','ville'],
    scores:[28,30,40,55,70,80,82,78,68,52,38,28], tempLo:5,  tempHi:17, rainDays:7, hi:"Soleil de minuit, archipel" },
  { id:'578', iso:'NO', name:'Norvège',      city:'Oslo',         cont:'eu', lat:59.91,  lon:10.75,   budget:3, tags:['nature','aventure'],
    scores:[30,32,40,55,72,82,84,80,70,55,40,30], tempLo:4,  tempHi:18, rainDays:7, hi:"Fjords, randonnée, aurores" },
  { id:'352', iso:'IS', name:'Islande',      city:'Reykjavík',    cont:'eu', lat:64.13,  lon:-21.95,  budget:3, tags:['nature','aventure'],
    scores:[40,42,48,58,72,82,84,80,72,55,45,40], tempLo:4,  tempHi:13, rainDays:9, hi:"Geysers, route 1, baleines" },
  { id:'191', iso:'HR', name:'Croatie',      city:'Split',        cont:'eu', lat:43.51,  lon:16.44,   budget:2, tags:['plage','culture'],
    scores:[40,45,55,68,80,86,84,82,78,72,55,42], tempLo:13, tempHi:23, rainDays:4, hi:"Dalmatie, Plitvice, Dubrovnik" },
  { id:'056', iso:'BE', name:'Belgique',     city:'Bruxelles',    cont:'eu', lat:50.85,  lon:4.35,    budget:2, tags:['culture','gastro'],
    scores:[35,40,50,62,72,75,72,70,66,55,42,35], tempLo:8,  tempHi:18, rainDays:9, hi:"Bruges, bières, gaufres" },
  { id:'040', iso:'AT', name:'Autriche',     city:'Vienne',       cont:'eu', lat:48.21,  lon:16.37,   budget:2, tags:['culture','nature'],
    scores:[32,38,48,62,75,80,78,75,70,58,42,32], tempLo:8,  tempHi:20, rainDays:7, hi:"Vienne, Tyrol, lacs alpins" },
  { id:'756', iso:'CH', name:'Suisse',       city:'Zurich',       cont:'eu', lat:47.37,  lon:8.55,    budget:3, tags:['nature','aventure'],
    scores:[40,45,55,65,75,80,82,80,75,62,48,40], tempLo:6,  tempHi:18, rainDays:8, hi:"Alpes, lacs, randonnée" },
  { id:'703', iso:'SK', name:'Slovaquie',    city:'Bratislava',   cont:'eu', lat:48.15,  lon:17.11,   budget:1, tags:['nature','culture'],
    scores:[30,35,48,62,75,80,78,75,70,55,40,30], tempLo:7,  tempHi:20, rainDays:6, hi:"Tatras, châteaux médiévaux" },
  { id:'616', iso:'PL', name:'Pologne',      city:'Cracovie',     cont:'eu', lat:50.06,  lon:19.94,   budget:1, tags:['culture','ville'],
    scores:[28,32,45,60,75,80,78,76,70,55,40,28], tempLo:6,  tempHi:19, rainDays:7, hi:"Cracovie, lacs masuriens" },

  // ASIE
  { id:'392', iso:'JP', name:'Japon',        city:'Kyōto',        cont:'as', lat:35.01,  lon:135.76,  budget:3, tags:['culture','gastro','ville'],
    scores:[50,68,82,90,84,68,60,58,72,84,78,55], tempLo:10, tempHi:22, rainDays:6, hi:"Cerisiers en avril, momiji en novembre" },
  { id:'410', iso:'KR', name:'Corée du Sud', city:'Séoul',        cont:'as', lat:37.57,  lon:126.98,  budget:2, tags:['culture','gastro','ville'],
    scores:[35,45,60,78,82,75,68,65,78,82,68,45], tempLo:8,  tempHi:21, rainDays:5, hi:"Printemps fleuri, K-food" },
  { id:'156', iso:'CN', name:'Chine',        city:'Pékin',        cont:'as', lat:39.91,  lon:116.4,   budget:2, tags:['culture','ville'],
    scores:[30,38,52,72,80,72,65,62,75,78,55,38], tempLo:5,  tempHi:22, rainDays:4, hi:"Grande Muraille, Yunnan" },
  { id:'356', iso:'IN', name:'Inde',         city:'Delhi',        cont:'as', lat:28.61,  lon:77.21,   budget:1, tags:['culture','aventure'],
    scores:[72,78,80,68,55,40,38,40,55,75,82,75], tempLo:12, tempHi:30, rainDays:1, hi:"Rajasthan, Kerala, Himalaya" },
  { id:'764', iso:'TH', name:'Thaïlande',    city:'Bangkok',      cont:'as', lat:13.75,  lon:100.5,   budget:1, tags:['plage','culture','gastro'],
    scores:[88,90,82,72,58,50,48,50,55,68,82,90], tempLo:22, tempHi:34, rainDays:2, hi:"Îles du sud, Chiang Mai" },
  { id:'704', iso:'VN', name:'Vietnam',      city:'Hanoï',        cont:'as', lat:21.03,  lon:105.85,  budget:1, tags:['culture','gastro','aventure'],
    scores:[68,72,78,75,65,52,48,52,68,82,86,78], tempLo:18, tempHi:28, rainDays:3, hi:"Baie d'Halong, Hôi An" },
  { id:'360', iso:'ID', name:'Indonésie',    city:'Bali',         cont:'as', lat:-8.34,  lon:115.09,  budget:1, tags:['plage','aventure','nature'],
    scores:[60,62,68,80,86,88,90,90,86,80,68,60], tempLo:23, tempHi:31, rainDays:6, hi:"Bali, Java, Komodo" },
  { id:'608', iso:'PH', name:'Philippines',  city:'Manille',      cont:'as', lat:14.6,   lon:120.98,  budget:1, tags:['plage','aventure'],
    scores:[80,85,86,82,70,55,50,52,58,68,78,82], tempLo:24, tempHi:32, rainDays:3, hi:"Palawan, Cebu, Bohol" },
  { id:'458', iso:'MY', name:'Malaisie',     city:'Kuala Lumpur', cont:'as', lat:3.14,   lon:101.69,  budget:1, tags:['plage','gastro'],
    scores:[72,78,80,78,72,72,72,72,72,72,68,72], tempLo:24, tempHi:32, rainDays:6, hi:"Bornéo, Langkawi, Penang" },
  { id:'784', iso:'AE', name:'Émirats A.U.', city:'Dubaï',        cont:'as', lat:25.2,   lon:55.27,   budget:3, tags:['ville','plage'],
    scores:[78,82,86,82,68,48,40,40,55,75,84,82], tempLo:14, tempHi:30, rainDays:1, hi:"Dubaï, Abu Dhabi, désert" },
  { id:'376', iso:'IL', name:'Israël',       city:'Tel Aviv',     cont:'as', lat:32.08,  lon:34.78,   budget:2, tags:['culture','plage'],
    scores:[58,62,72,82,86,80,72,70,80,84,72,60], tempLo:14, tempHi:25, rainDays:2, hi:"Jérusalem, Mer Morte" },
  { id:'400', iso:'JO', name:'Jordanie',     city:'Amman',        cont:'as', lat:31.95,  lon:35.93,   budget:2, tags:['culture','aventure'],
    scores:[50,55,68,82,88,80,72,70,82,86,72,55], tempLo:12, tempHi:25, rainDays:1, hi:"Pétra, Wadi Rum" },
  { id:'524', iso:'NP', name:'Népal',        city:'Katmandou',    cont:'as', lat:27.7,   lon:85.32,   budget:1, tags:['aventure','nature','culture'],
    scores:[60,65,75,82,72,55,48,50,72,86,82,68], tempLo:8,  tempHi:22, rainDays:2, hi:"Himalaya, Pokhara, treks" },
  { id:'050', iso:'BD', name:'Bangladesh',   city:'Dhaka',        cont:'as', lat:23.81,  lon:90.41,   budget:1, tags:['culture','aventure'],
    scores:[65,72,72,62,52,42,40,42,52,68,72,68], tempLo:15, tempHi:30, rainDays:2, hi:"Sundarbans, Dacca" },

  // AFRIQUE
  { id:'504', iso:'MA', name:'Maroc',        city:'Marrakech',    cont:'af', lat:31.63,  lon:-7.99,   budget:1, tags:['culture','aventure','gastro'],
    scores:[58,65,75,85,91,82,72,72,84,88,72,58], tempLo:14, tempHi:25, rainDays:2, hi:"Marrakech, Atlas, Sahara" },
  { id:'788', iso:'TN', name:'Tunisie',      city:'Tunis',        cont:'af', lat:36.81,  lon:10.18,   budget:1, tags:['plage','culture'],
    scores:[52,58,68,78,86,82,72,72,82,80,65,55], tempLo:13, tempHi:25, rainDays:2, hi:"Sidi Bou Saïd, Djerba" },
  { id:'818', iso:'EG', name:'Égypte',       city:'Le Caire',     cont:'af', lat:30.04,  lon:31.24,   budget:1, tags:['culture','plage'],
    scores:[72,78,82,82,72,55,50,50,68,82,80,72], tempLo:12, tempHi:28, rainDays:0, hi:"Pyramides, Nil, mer Rouge" },
  { id:'710', iso:'ZA', name:'Afrique du Sud',city:'Le Cap',      cont:'af', lat:-33.92, lon:18.42,   budget:2, tags:['nature','aventure','gastro'],
    scores:[80,82,80,72,58,52,50,52,62,75,82,84], tempLo:16, tempHi:26, rainDays:3, hi:"Cape Town, safari, vins" },
  { id:'404', iso:'KE', name:'Kenya',        city:'Nairobi',      cont:'af', lat:-1.29,  lon:36.82,   budget:2, tags:['aventure','nature'],
    scores:[78,80,76,68,62,72,78,80,82,80,72,70], tempLo:14, tempHi:26, rainDays:4, hi:"Masai Mara, grand migration" },
  { id:'834', iso:'TZ', name:'Tanzanie',     city:'Dar es Salaam',cont:'af', lat:-6.79,  lon:39.21,   budget:2, tags:['aventure','plage','nature'],
    scores:[72,75,72,62,55,70,78,82,86,82,72,70], tempLo:18, tempHi:30, rainDays:3, hi:"Serengeti, Zanzibar, Kili" },
  { id:'266', iso:'NA', name:'Namibie',      city:'Windhoek',     cont:'af', lat:-22.56, lon:17.08,   budget:2, tags:['aventure','nature'],
    scores:[68,70,75,82,86,82,78,80,84,80,72,68], tempLo:10, tempHi:25, rainDays:0, hi:"Sossusvlei, Skeleton Coast" },
  { id:'480', iso:'MU', name:'Maurice',      city:'Port-Louis',   cont:'af', lat:-20.16, lon:57.5,    budget:3, tags:['plage','nature'],
    scores:[68,68,72,82,88,86,82,82,86,90,82,72], tempLo:20, tempHi:28, rainDays:5, hi:"Lagons, randos, Le Morne" },

  // AMÉRIQUE NORD
  { id:'840', iso:'US', name:'États-Unis',   city:'New York',     cont:'na', lat:40.71,  lon:-74.0,   budget:3, tags:['culture','ville','aventure'],
    scores:[40,45,55,68,78,80,76,74,78,72,55,40], tempLo:9,  tempHi:22, rainDays:8, hi:"NY, Californie, parcs nationaux" },
  { id:'124', iso:'CA', name:'Canada',       city:'Montréal',     cont:'na', lat:45.5,   lon:-73.57,  budget:3, tags:['nature','ville','aventure'],
    scores:[28,32,42,58,72,80,82,80,72,60,42,28], tempLo:6,  tempHi:18, rainDays:8, hi:"Rocheuses, Québec, Maritimes" },
  { id:'484', iso:'MX', name:'Mexique',      city:'Mexico',       cont:'na', lat:19.43,  lon:-99.13,  budget:1, tags:['culture','plage','gastro'],
    scores:[78,82,84,80,72,62,58,60,68,78,82,80], tempLo:11, tempHi:25, rainDays:3, hi:"Yucatán, CDMX, Oaxaca" },
  { id:'188', iso:'CR', name:'Costa Rica',   city:'San José',     cont:'na', lat:9.93,   lon:-84.08,  budget:2, tags:['nature','aventure','plage'],
    scores:[88,90,86,78,62,58,55,55,52,55,72,86], tempLo:18, tempHi:28, rainDays:2, hi:"Volcans, Pacifique, Caraïbes" },
  { id:'192', iso:'CU', name:'Cuba',         city:'La Havane',    cont:'na', lat:23.13,  lon:-82.38,  budget:1, tags:['culture','plage','gastro'],
    scores:[80,84,86,82,72,62,60,58,55,68,80,82], tempLo:18, tempHi:28, rainDays:2, hi:"La Havane, Viñales, Trinidad" },

  // AMÉRIQUE SUD
  { id:'076', iso:'BR', name:'Brésil',       city:'Rio',          cont:'sa', lat:-22.9,  lon:-43.17,  budget:2, tags:['plage','culture','aventure'],
    scores:[68,72,72,75,78,75,72,75,72,68,68,70], tempLo:22, tempHi:30, rainDays:5, hi:"Rio, Amazonie, Salvador" },
  { id:'032', iso:'AR', name:'Argentine',    city:'Buenos Aires', cont:'sa', lat:-34.6,  lon:-58.38,  budget:1, tags:['culture','aventure','gastro'],
    scores:[78,80,78,72,62,55,52,55,62,72,80,82], tempLo:14, tempHi:25, rainDays:5, hi:"Patagonie, tango, vins" },
  { id:'152', iso:'CL', name:'Chili',        city:'Santiago',     cont:'sa', lat:-33.45, lon:-70.67,  budget:2, tags:['aventure','nature','gastro'],
    scores:[78,82,82,72,60,52,50,52,62,72,80,80], tempLo:12, tempHi:24, rainDays:2, hi:"Atacama, Patagonie, Valparaíso" },
  { id:'604', iso:'PE', name:'Pérou',        city:'Lima',         cont:'sa', lat:-12.04, lon:-77.03,  budget:1, tags:['culture','aventure'],
    scores:[72,74,75,80,78,72,68,68,72,78,80,75], tempLo:15, tempHi:26, rainDays:1, hi:"Machu Picchu, Cuzco, Sacré" },
  { id:'170', iso:'CO', name:'Colombie',     city:'Bogotá',       cont:'sa', lat:4.71,   lon:-74.07,  budget:1, tags:['culture','plage','aventure'],
    scores:[78,80,75,70,68,72,78,78,72,72,75,78], tempLo:12, tempHi:24, rainDays:4, hi:"Cartagena, café, Amazonas" },
  { id:'858', iso:'UY', name:'Uruguay',      city:'Montevideo',   cont:'sa', lat:-34.9,  lon:-56.18,  budget:2, tags:['plage','culture'],
    scores:[80,82,80,72,62,55,52,55,62,72,80,82], tempLo:14, tempHi:25, rainDays:5, hi:"Punta del Este, Colonia" },

  // OCÉANIE
  { id:'036', iso:'AU', name:'Australie',    city:'Sydney',       cont:'oc', lat:-33.87, lon:151.21,  budget:3, tags:['plage','aventure','ville'],
    scores:[78,82,82,78,72,68,68,72,78,82,82,80], tempLo:14, tempHi:24, rainDays:5, hi:"Sydney, GBR, Outback" },
  { id:'554', iso:'NZ', name:'Nouv.-Zélande',city:'Auckland',     cont:'oc', lat:-36.85, lon:174.76,  budget:3, tags:['aventure','nature'],
    scores:[82,84,82,72,60,52,52,55,65,75,82,84], tempLo:11, tempHi:21, rainDays:6, hi:"Fjordland, Queenstown" },
  { id:'242', iso:'FJ', name:'Fidji',        city:'Suva',         cont:'oc', lat:-18.14, lon:178.44,  budget:3, tags:['plage','nature'],
    scores:[68,70,72,75,82,88,90,90,86,80,72,68], tempLo:22, tempHi:30, rainDays:5, hi:"Yasawa, plongée, lagons" },
];

/** Merge the hand-curated baseline with overrides from climate.json (if any). */
export const countries: Country[] = COUNTRIES_BASELINE.map(c => {
  const o = (climateOverrides as Record<string, Partial<Country>>)[c.iso];
  return o ? { ...c, ...o } : c;
});

export const inspirePicks: Record<Tag, string[]> = {
  plage:    ['MA','GR','HR','PT','MU'],
  culture:  ['JP','IT','PT','MA','PE'],
  aventure: ['IS','NP','NA','NZ','CR'],
  gastro:   ['IT','JP','FR','PE','VN'],
  ville:    ['JP','GB','NL','US','AE'],
  nature:   ['IS','NO','NZ','CR','SE'],
};

export const agents: Agent[] = [
  { id:'meteo',  name:'Météo',    color:'#22b07a', icon:'☼' },
  { id:'budget', name:'Budget',   color:'#e7b54b', icon:'€' },
  { id:'safety', name:'Sécurité', color:'#d97757', icon:'◉' },
  { id:'plan',   name:'Planning', color:'#8ab4ff', icon:'❖' },
];

export function countryById(id: string): Country | null {
  return countries.find(c => c.id === id) || null;
}
export function countryByIso(iso: string): Country | null {
  return countries.find(c => c.iso === iso) || null;
}
